#!/bin/bash

if [ ! -f $HOME/git-watched.txt ] ; then
  echo "USAGE: Create a file git-watched.txt in the home dir with list"
  echo "   of directories to watch (1 dir per line)"
  exit 1
fi

res=""

while read gitdir
do
  if [ ! $gitdir == "" ] && [ -d $gitdir ] && [ ! $gitdir == $'\n' ]; then
    cd $gitdir
    status=`git status 2 | grep -c "Your branch is ahead of"`
    if [ $status -ne 0 ]; then
      dirname=`basename $gitdir`
      res="$res\n$dirname"
    fi
  else
    if [ ! $gitdir == "" ]; then
      echo "Invalid record in git-watched: $gitdir"
      exit 1
    fi
  fi
done < $HOME/git-watched.txt

if [ ! $res == "" ]; then
  notify-send -i face-angry "Git Reminder" "Forgot to push:\n\n $res"
fi
