#!/bin/sh

# Script executes git commands recursively on submodules

# Usage samples:
#   gitr status
#   gitr commit -a -m "some comment"
#   gitr push

case "$1" in
	"init") CMD="submodule update --init" ;;
	*) CMD="$*" ;;
esac

git $CMD
git submodule foreach "$0" $CMD

