#!/usr/bin/env bash

# Get all authors from SVN repository in the current directory

authors=$(svn log -q | grep -e '^r' | awk 'BEGIN { FS = "|" } ; { print $2 }' | sort | uniq)
for author in ${authors}; do
  echo "${author} = ${author} <${author}@example.com>";
done

